### ISSUE TITLE
Update to conf.py file

### ISSUE THREAD

**Issue by meker12** [objectrocket/documentation#14]
Consider including the  `text_sectionchars` parameter in the config.py file. Seems like it would be helpful to include it so people can keep track of the syntax when editing. I noticed that different projects use different conventions for these identifiers.

**text_sectionchars**
A string of 7 characters that should be used for underlining sections. The first character is used for first-level headings, the second for second-level headings and so on.  

The default is '*=-~"+`'.

(Source: [Python - Sphinx config documentation](http://www.pythondoc.com/sphinx/config.html#confval-text_sectionchars))

The default is '*=-~"+`'.

**Comment by SethSanchez** [comment]
Hi!

I'm very sorry we didn't merge this last year, but we've been working on getting the proper maintainers in line. If you send us an email at support@objectrocket.com with your name, address, and tshirt size, we'll be happy to send you a shirt now that it's fixed!
