### ISSUE TITLE
Update directions to account for new ObjectRocket UI

### ISSUE THREAD

**Issue by jtharpla** [objectrocket/documentation#29]
Examples of what needs updating:

http://docs.objectrocket.com/getting_started.html#create-a-database
"The first step is to create a database, and give it a username and password credentials so you can get connected. Head to the instances page then click on the instance you would like to add a database to. Use the Add Database button on the databases page to add a database. " <-- there is no databases page

http://docs.objectrocket.com/getting_started.html#add-an-acl
"Head to the instances page then click on the instance you would like to add a ACL to. Select the ACL tab, and the add ACL button." <-- there is no ACL tab

I'm sure there are other references we need to fix like this to account for stuff that has moved with the UI redesign

**Comment by SethSanchez** [comment]
Fixed in #47
