### ISSUE TITLE
Missing stats APIv2 calls

### ISSUE THREAD

**Issue by SethSanchez** [objectrocket/documentation#61]
@heydonovan, do you still have those lying around? Looks like we have some customer interest after all.

**Comment by heydonovan** [comment]
We have these stats: http://objectrocket.com/docs/api_v2_general_resources.html#get-both-the-replset-infrastructure-and-the-list-of-stats-for-a-host

Do you mean the `/dashboards/` resources? https://github.com/objectrocket/api/blob/develop/api/v2/blueprint.py#L72

**Comment by SethSanchez** [comment]
@heydonovan Did you make any headway on this?

**Comment by SethSanchez** [comment]
Decided not to go this route, closing.
